import {
	WS_CONNECTION_START,
	WS_CONNECTION_CLOSE,
	WS_SEND_MESSAGE,
	WS_CONNECTION_SUCCESS,
	WS_CONNECTION_ERROR,
	WS_CONNECTION_CLOSED,
	WS_GET_MESSAGE
} from '../constants/ws';


export const wsActions = {
	wsInit: WS_CONNECTION_START,
	wsClose: WS_CONNECTION_CLOSE,
	wsSendMessage: WS_SEND_MESSAGE,
	onOpen: WS_CONNECTION_SUCCESS,
	onClose: WS_CONNECTION_CLOSED,
	onError: WS_CONNECTION_ERROR,
	onMessage: WS_GET_MESSAGE
};