const Actions = {
  GET_INGREDIENTS: "GET_INGREDIENTS",
  GET_INGREDIENTS_SUCCESS: "GET_INGREDIENTS_SUCCESS",
  GET_INGREDIENTS_ERROR: "GET_INGREDIENTS_ERROR",

  DRAG_INGREDIENT: "DRAG_INGREDIENT",
  DROP_INGREDIENT: "DROP_INGREDIENT",

  ADD_INGREDIENT_TO_CONSTRUCTOR: "ADD_INGREDIENT_TO_CONSTRUCTOR",
  REMOVE_INGREDIENT_FROM_CONSTRUCTOR: "REMOVE_INGREDIENT_FROM_CONSTRUCTOR",
  RESET_CONSTRUCTOR_INGREDIENTS: "RESET_CONSTRUCTOR_INGREDIENTS",
  ADD_BUN_TO_CONSTRUCTOR: "ADD_BUN_TO_CONSTRUCTOR",
  CHANGE_CONSTRUCTOR_INGREDIENT_POSITION:
    "CHANGE_CONSTRUCTOR_INGREDIENT_POSITION",

  SET_DETAILED_INGREDIENT: "SET_DETAILED_INGREDIENT",
  RESET_DETAILED_INGREDIENT: "RESET_DETAILED_INGREDIENT",

  POST_ORDER: "POST_ORDER",
  POST_ORDER_SUCCESS: "POST_ORDER_SUCCESS",
  POST_ORDER_ERROR: "POST_ORDER_ERROR",
  RESET_ORDER_NUMBER: "RESET_ORDER_NUMBER",

  LOGIN: 'auth/LOGIN',
  LOGIN_SUCCESS: 'auth/LOGIN_SUCCESS',
  LOGIN_ERROR: 'auth/LOGIN_ERROR',
  RESET_AUTH: 'auth/RESET_AUTH',

  REFRESH_TOKEN: 'auth/REFRESH_TOKEN',
  REFRESH_TOKEN_SUCCESS: 'auth/REFRESH_TOKEN_SUCCESS',
  REFRESH_TOKEN_ERROR: 'auth/REFRESH_TOKEN_ERROR',

  REGISTER_USER: 'auth/REGISTER_USER',
  REGISTER_USER_SUCCESS: 'auth/REGISTER_USER_SUCCESS',
  REGISTER_USER_ERROR: 'auth/REGISTER_USER_ERROR',

  LOGOUT: 'auth/LOGOUT',
  LOGOUT_SUCCESS: 'auth/LOGOUT_SUCCESS',
  LOGOUT_ERROR: 'auth/LOGOUT_ERROR',

  REQUEST_PASSWORD_RESET_CODE: 'auth/REQUEST_PASSWORD_RESET_CODE',
  REQUEST_PASSWORD_RESET_CODE_SUCCESS: 'auth/REQUEST_PASSWORD_RESET_CODE_SUCCESS',
  REQUEST_PASSWORD_RESET_CODE_ERROR: 'auth/REQUEST_PASSWORD_RESET_CODE_ERROR',

  PASSWORD_RESET: 'auth/REQUEST_PASSWORD_RESET',
  PASSWORD_RESET_SUCCESS: 'auth/REQUEST_PASSWORD_RESET_SUCCESS',
  PASSWORD_RESET_ERROR: 'auth/REQUEST_PASSWORD_RESET_ERROR',

  FETCH_USER_INFO: 'auth/FETCH_USER_INFO',
  FETCH_USER_INFO_SUCCESS: 'auth/FETCH_USER_INFO_SUCCESS',
  FETCH_USER_INFO_ERROR: 'auth/FETCH_USER_INFO_ERROR',

  PATCH_USER_INFO: 'auth/PATCH_USER_INFO',
  PATCH_USER_INFO_SUCCESS: 'auth/PATCH_USER_INFO_SUCCESS',
  PATCH_USER_INFO_ERROR: 'auth/PATCH_USER_INFO_ERROR'
};

export default Actions;
