const Actions = {
  GET_INGREDIENTS: "GET_INGREDIENTS",
  GET_INGREDIENTS_SUCCESS: "GET_INGREDIENTS_SUCCESS",
  GET_INGREDIENTS_ERROR: "GET_INGREDIENTS_ERROR",

  DRAG_INGREDIENT: "DRAG_INGREDIENT",
  DROP_INGREDIENT: "DROP_INGREDIENT",

  ADD_INGREDIENT_TO_CONSTRUCTOR: "ADD_INGREDIENT_TO_CONSTRUCTOR",
  REMOVE_INGREDIENT_FROM_CONSTRUCTOR: "REMOVE_INGREDIENT_FROM_CONSTRUCTOR",
  RESET_CONSTRUCTOR_INGREDIENTS: "RESET_CONSTRUCTOR_INGREDIENTS",
  ADD_BUN_TO_CONSTRUCTOR: "ADD_BUN_TO_CONSTRUCTOR",
  CHANGE_CONSTRUCTOR_INGREDIENT_POSITION:
    "CHANGE_CONSTRUCTOR_INGREDIENT_POSITION",

  SET_DETAILED_INGREDIENT: "SET_DETAILED_INGREDIENT",
  RESET_DETAILED_INGREDIENT: "RESET_DETAILED_INGREDIENT",

  POST_ORDER: "POST_ORDER",
  POST_ORDER_SUCCESS: "POST_ORDER_SUCCESS",
  POST_ORDER_ERROR: "POST_ORDER_ERROR",
  RESET_ORDER_NUMBER: "RESET_ORDER_NUMBER",
};

export default Actions;
