export const GET_INGREDIENTS: "GET_INGREDIENTS" = "GET_INGREDIENTS";
export const GET_INGREDIENTS_SUCCESS: "GET_INGREDIENTS_SUCCESS" =
  "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_ERROR: "GET_INGREDIENTS_ERROR" =
  "GET_INGREDIENTS_ERROR";

export const DRAG_INGREDIENT: "DRAG_INGREDIENT" = "DRAG_INGREDIENT";
export const DROP_INGREDIENT: "DROP_INGREDIENT" = "DROP_INGREDIENT";

export const ADD_INGREDIENT_TO_CONSTRUCTOR: "ADD_INGREDIENT_TO_CONSTRUCTOR" =
  "ADD_INGREDIENT_TO_CONSTRUCTOR";
export const REMOVE_INGREDIENT_FROM_CONSTRUCTOR: "REMOVE_INGREDIENT_FROM_CONSTRUCTOR" =
  "REMOVE_INGREDIENT_FROM_CONSTRUCTOR";
export const RESET_CONSTRUCTOR_INGREDIENTS: "RESET_CONSTRUCTOR_INGREDIENTS" =
  "RESET_CONSTRUCTOR_INGREDIENTS";
export const ADD_BUN_TO_CONSTRUCTOR: "ADD_BUN_TO_CONSTRUCTOR" =
  "ADD_BUN_TO_CONSTRUCTOR";
export const CHANGE_CONSTRUCTOR_INGREDIENT_POSITION: "CHANGE_CONSTRUCTOR_INGREDIENT_POSITION" =
  "CHANGE_CONSTRUCTOR_INGREDIENT_POSITION";

export const SET_DETAILED_INGREDIENT: "SET_DETAILED_INGREDIENT" = "SET_DETAILED_INGREDIENT";
export const RESET_DETAILED_INGREDIENT: "RESET_DETAILED_INGREDIENT" = "RESET_DETAILED_INGREDIENT";

export const POST_ORDER: "POST_ORDER" = "POST_ORDER";
export const POST_ORDER_SUCCESS: "POST_ORDER_SUCCESS" = "POST_ORDER_SUCCESS";
export const POST_ORDER_ERROR: "POST_ORDER_ERROR" = "POST_ORDER_ERROR";
export const RESET_ORDER_NUMBER: "RESET_ORDER_NUMBER" = "RESET_ORDER_NUMBER";

export const LOGIN: "auth/LOGIN" = "auth/LOGIN";
export const LOGIN_SUCCESS: "auth/LOGIN_SUCCESS" = "auth/LOGIN_SUCCESS";
export const LOGIN_ERROR: "auth/LOGIN_ERROR" = "auth/LOGIN_ERROR";
export const RESET_AUTH: "auth/RESET_AUTH" = "auth/RESET_AUTH";

export const REFRESH_TOKEN: "auth/REFRESH_TOKEN" = "auth/REFRESH_TOKEN";
export const REFRESH_TOKEN_SUCCESS: "auth/REFRESH_TOKEN_SUCCESS" = "auth/REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_ERROR: "auth/REFRESH_TOKEN_ERROR" = "auth/REFRESH_TOKEN_ERROR";

export const REGISTER_USER: "auth/REGISTER_USER" = "auth/REGISTER_USER";
export const REGISTER_USER_SUCCESS: "auth/REGISTER_USER_SUCCESS" = "auth/REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR: "auth/REGISTER_USER_ERROR" = "auth/REGISTER_USER_ERROR";

export const LOGOUT: "auth/LOGOUT" = "auth/LOGOUT";
export const LOGOUT_SUCCESS: "auth/LOGOUT_SUCCESS" = "auth/LOGOUT_SUCCESS";
export const LOGOUT_ERROR: "auth/LOGOUT_ERROR" = "auth/LOGOUT_ERROR";

export const REQUEST_PASSWORD_RESET_CODE: "auth/REQUEST_PASSWORD_RESET_CODE" = "auth/REQUEST_PASSWORD_RESET_CODE";
export const REQUEST_PASSWORD_RESET_CODE_SUCCESS: "auth/REQUEST_PASSWORD_RESET_CODE_SUCCESS" = "auth/REQUEST_PASSWORD_RESET_CODE_SUCCESS";
export const REQUEST_PASSWORD_RESET_CODE_ERROR: "auth/REQUEST_PASSWORD_RESET_CODE_ERROR" = "auth/REQUEST_PASSWORD_RESET_CODE_ERROR";

export const PASSWORD_RESET: "auth/REQUEST_PASSWORD_RESET" = "auth/REQUEST_PASSWORD_RESET";
export const PASSWORD_RESET_SUCCESS: "auth/REQUEST_PASSWORD_RESET_SUCCESS" = "auth/REQUEST_PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_ERROR: "auth/REQUEST_PASSWORD_RESET_ERROR" = "auth/REQUEST_PASSWORD_RESET_ERROR";

export const FETCH_USER_INFO: "auth/FETCH_USER_INFO" = "auth/FETCH_USER_INFO";
export const FETCH_USER_INFO_SUCCESS: "auth/FETCH_USER_INFO_SUCCESS" = "auth/FETCH_USER_INFO_SUCCESS";
export const FETCH_USER_INFO_ERROR: "auth/FETCH_USER_INFO_ERROR" = "auth/FETCH_USER_INFO_ERROR";

export const PATCH_USER_INFO: "auth/PATCH_USER_INFO" = "auth/PATCH_USER_INFO";
export const PATCH_USER_INFO_SUCCESS: "auth/PATCH_USER_INFO_SUCCESS" = "auth/PATCH_USER_INFO_SUCCESS";
export const PATCH_USER_INFO_ERROR: "auth/PATCH_USER_INFO_ERROR" = "auth/PATCH_USER_INFO_ERROR";
